version: '3.5'

services:

  ## Postgresql instance
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5434:5432
    networks:
      - single-site-network
    restart: unless-stopped
  
  ## Redis
  redis:
    image: redis:6.2-alpine
    volumes:
      - redis:/data
    ports:
      - 6373:6379
    restart: unless-stopped

  ## Minio s3 like object storage  
  minio:
    image: 'bitnami/minio:2022'
    volumes:
      - minio-data:/data
      - minio-certs:/certs
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_FORCE_NEW_KEYS=yes
      - MINIO_DEFAULT_BUCKETS=${MINIO_SERVER_ACCESS_KEY:-default-buckets:public}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minio-root-user}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minio-root-password}
    networks:
      - single-site-network
    restart: unless-stopped

  ## Caddy
  caddy:
    image: caddy:alpine
    command:
      [
        'caddy',
        'run',
        '--config',
        '/etc/caddy/config.json',
        '--resume'
      ]
    restart: unless-stopped
    ports:
      - 8080:80
      - 2019:2019
    networks:
      - single-site-network
    volumes:
      - ./resources/caddy/config.json:/etc/caddy/config.json
      - ./resources/caddy/sites:/sites
      - ./resources/caddy/data:/data
      - ./resources/caddy/config:/config

networks:
  single-site-network:
    driver: bridge

volumes:
  pgdata:
  redis:
  minio-data:
  minio-certs:
